### ISSUE TITLE
yeast data from tutorial

### ISSUE THREAD

**Issue by LouisGil** [flatironinstitute/inferelator#13]
Hi,

Im trying to go through the tutorial and the link containing the yeast data is dead:
wget https://www.dropbox.com/s/dhj4amz0wcfdn58/expression.tsv -P data/yeast

Thanks

**Comment by asistradition** [comment]
Thanks for letting us know. The yeast data is on Zenodo and is available at this DOI: https://doi.org/10.5281/zenodo.3247753

We'll update the tutorial.
