### ISSUE TITLE
Tutorial for multitask learning workflow

### ISSUE THREAD

**Issue by daria-dc** [flatironinstitute/inferelator#18]
Hi, 

I would like to try the multitask learning workflow that was used in the publication "Multi-study inference of regulatory networks for more accurate models of gene regulation"... however, I can not find any instructions or tutorial how to run it. Could you provide a tutorial similar to the one for single task learning?

Furthermore, do you know if very different sample sizes between data sets affect the outcome?

Thanks in advance!

**Comment by asistradition** [comment]
I'm still working up the tutorial and documentation for multitask learning. It should be available with the next minor version release (if not this week, than the first week of January). 

My general rule of thumb is that I have to have enough data in each task to make reasonable inference from a regression model; after that the size difference between tasks is not usually a big concern.

**Comment by asistradition** [comment]
There is now a tutorial (https://inferelator.readthedocs.io/en/latest/tutorial.html) and several example scripts for multitask as of v0.3.2 (PR #19)
